use_frameworks!

target 'BigIntegerSwift_Example' do
  pod 'BigIntegerSwift', :path => '../'

  target 'BigIntegerSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
