language: objective-c
osx_image: xcode9.2
xcode_project:
xcode_scheme: BigInteger
xcode_sdk: iphonesimulator11.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="BigInteger"
  - OSX_FRAMEWORK_SCHEME="BigIntegerMac"
  - PROJECT="BigInteger.xcodeproj"
  matrix:
  - DESTINATION="OS=11.1,name=iPhone 6"            SCHEME="$IOS_FRAMEWORK_SCHEME"       ACTION="test"
  - DESTINATION="arch=x86_64"                      SCHEME="$OSX_FRAMEWORK_SCHEME"       ACTION="build"

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pip install --user codecov
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail
  - xcodebuild -scheme "$SCHEME" -project "$PROJECT" -destination "$DESTINATION" clean $ACTION | xcpretty

after_success:
  - pod lib lint
  - bash <(curl -s https://codecov.io/bash)
