language: objective-c
osx_image: xcode9.2
xcode_project:
xcode_scheme: BigInteger
xcode_sdk: iphonesimulator11.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=BigInteger.xcodeproj
  - SCHEME="BigInteger"
  - DESTINATION="OS=11.1,name=iPhone X"
  #- EXAMPLE_SCHEME="iOS Example"


before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pip install --user codecov
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail
  - xcodebuild -scheme "$SCHEME" -project "$PROJECT" -destination "$DESTINATION" build test | xcpretty
  - pod lib lint


after_success:
  - bash <(curl -s https://codecov.io/bash)
